
export const locationList = new Map( [
  [ 'Antre of Adjournment', 'Malchor\'s Leap' ],
  [ 'Troll\'s Revenge', 'Lion\'s Arch' ],
  [ 'Urmaug\'s Secret', 'Lion\'s Arch' ],
  [ 'Weyandt\'s Revenge', 'Lion\'s Arch' ],
  [ 'Behem Gauntlet', 'Blazeridge Steppes' ],
  [ 'Branded Mine', 'Fields of Ruin' ],
  [ 'Wall Breach Blitz', 'Diessa Plateau' ],
  [ 'Buried Archives', 'Cursed Shore' ],
  [ 'Chaos Crystal Cavern', 'Iron Marches' ],
  [ 'The Collapsed Observatory', 'Kessex Hills' ],
  [ 'Craze\'s Folly', 'Blazeridge Steppes' ],
  [ 'Tribulation Caverns', 'Dredgehaunt Cliffs' ],
  [ 'Crimson Plateau', 'Diessa Plateau' ],
  [ 'Dark Reverie', 'Caledon Forest' ],
  [ 'Demongrub Pits', 'Queensdale' ],
  [ 'Emerald Sanctum', 'Alpine Borderlands' ],
  [ 'Fawcett\'s Bounty', 'Harathi Hinterlands' ],
  [ 'Fawcett\'s Revenge', 'Harathi Hinterlands' ],
  [ 'Hexfoundry Unhinged', 'Sparkfly Fen' ],
  [ 'Goemm\'s Lab', 'Metrica Province' ],
  [ 'Conundrum Cubed', 'Mount Maelstrom' ],
  [ 'Grendich Gamble', 'Diessa Plateau' ],
  [ 'Griffonrook Run', 'Lornar\'s Pass' ],
  [ 'King Jalis\'s Refuge', 'Snowden Drifts' ],
  [ 'Loreclaw Expanse', 'Plains of Ashford' ],
  [ 'Morgan\'s Leap', 'Caledon Forest' ],
  [ 'Obsidian Sanctum', 'World vs. World' ],
  [ 'Pig Iron Quarry', 'Fireheart Rise' ],
  [ 'Professor Portmatt\'s Lab', 'Bloodtide Coast' ],
  [ 'Sapphire Sanctum', 'Alpine Borderlands' ],
  [ 'Scavenger\'s Chasm', 'Malchor\'s Leap' ],
  [ 'Only Zuhl', 'Timberline Falls' ],
  [ 'Shaman\'s Rookery', 'Wayfarer Foothills' ],
  [ 'Shattered Ice Ruins', 'Frostgorge Sound' ],
  [ 'Skipping Stones', 'Southsun Cove' ],
  [ 'Spekks\'s Laboratory', 'Caledon Forest' ],
  [ 'Spelunker\'s Delve', 'Caledon Forest' ],
  [ 'Swashbuckler\'s Cove', 'Gendarran Fields' ],
  [ 'Hidden Garden', 'Mount Maelstrom' ],
  [ 'Coddler\'s Cove', 'Timberline Falls' ],
  [ 'Tribulation Rift Scaffolding', 'Dredgehaunt Cliffs' ],
  [ 'Under New Management', 'Southsun Cove' ],
  [ 'Vizier\'s Tower', 'Straits of Devastation' ],
  [ 'Not So Secret', 'Gendarran Fields' ] ]
) ;
